name: "Test Action"
description: "test action"
runs:
  using: "composite"
  steps:
    - name: Only do this on push to protected main branch
      if: ${{ github.event_name == 'push' and github.ref == 'refs/heads/main' }}
      run: |
        This is sensitive!
      shell: bash
